name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: nat997/my-docker-repo:latest

    - name: Run unit tests
      run: |
        # Add commands to run your unit tests here

