name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Start Docker Compose
      run: docker-compose up -d 
    - name: Execute PHP test
      run: docker exec exo_devops_php php test.php
